module.exports.descriptors = [
    'Savory',
    'Spicy',
    'Golden',
    'Sweet',
    'Smoky',
    'Zesty',
    'Crispy',
    'Juicy',
    'Sizzling',
    'Flavorful',
    'Tangy',
    'Baked',
    'Grilled',
    'Mouthwatering',
    'Velvety',
    'Delicious',
    'Succulent',
    'Gourmet',
    'Savory',
    'Exquisite',
    'Aromatic'
];

module.exports.foodNames = [
    'Apple Pie',
    'Risotto',
    'Roast',
    'Sushi',
    'Burger',
    'Curry',
    'Tiramisu',
    'Pasta',
    'Enchiladas',
    'Muffin',
    'Taco',
    'Pancake',
    'Cheesecake',
    'Lasagna',
    'Smoothie',
    'Fajitas',
    'Crepes',
    'Gnocchi',
    'Sorbet',
    'Bruschetta',
    'Fondue'
];